swagger: "2.0"
info:
  version: "1.0.0"
  title: "api document for disaster response project"
  contact:
    email: "cenkai29@gmail.com"
basePath: "/"
schemes:
- "https"

paths:
  /message/message_classification/v1:
    post:
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: object
          properties:
            text:
             type: string
             description: message text that need tot be classified
             example: 'Good evening, when will I get help? We need clean water, food and tents. answer me please. thanks'
      summary: classify message
      responses:
        200:
          schema:
            type: object
            description: \"0\" is for not hit and \"1\" is hit
            example: {
              "aid_centers": "0",
              "aid_related": "1",
              "buildings": "0",
              "child_alone": "1",
              "clothing": "0",
              "cold": "0",
              "death": "0",
              "earthquake": "0",
              "electricity": "0",
              "fire": "0",
              "floods": "0",
              "food": "1",
              "hospitals": "0",
              "infrastructure_related": "0",
              "medical_help": "0",
              "medical_products": "0",
              "military": "0",
              "missing_people": "0",
              "money": "0",
              "offer": "0",
              "other_aid": "0",
              "other_infrastructure": "0",
              "other_weather": "1",
              "refugees": "0",
              "related": "0",
              "request": "1",
              "search_and_rescue": "0",
              "security": "0",
              "shelter": "0",
              "shops": "0",
              "storm": "0",
              "tools": "0",
              "transport": "0",
              "water": "1",
              "weather_related": "0"
            }
          description: classification result
  
  /message/message_stat/v1:
    post:
      summary: get statistical analysis of historical messages
      responses:
        200:
          schema:
            type: object
            properties:
              category_count:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    value:
                      type: number
              genre_distribution:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    value:
                      type: number
          description: stat result

