swagger: "2.0"
info:
  version: "1.0.0"
  title: "api document for disaster response project"
  contact:
    email: "cenkai29@gmail.com"
basePath: "/"
schemes:
- "https"

paths:
  /image/dog_breed_classification/v1:
    post:
      summary: "get the classification result of image recognition"
      consumes:
        - multipart/form-data
      parameters:
      - name: file
        in: formData
        type: file
      responses:
        200:
          schema:
            type: object
            properties:
              result:
                type: string
                example: "This image looks like a dog. And the breed is: Golden_retriever"
          description: the result of image recognition
